/**
 * Meta WhatsApp Cloud API helpers.
 * All outbound calls use resilientFetch: 8s timeout and at most one
 * retry for transient network/5xx failures.
 */

import { resilientFetch } from '@/lib/security/resilient-fetch'
import type { MessageTemplate } from '@/types'
import { buildSendComponents, type SendTimeParams } from './template-send-builder'
import type { MetaTemplateSubmitPayload } from './template-components'

const META_API_VERSION = 'v21.0'
const META_API_BASE = `https://graph.facebook.com/${META_API_VERSION}`

export interface MetaSendResult { messageId: string }
export interface MetaPhoneInfo { id: string; display_phone_number: string; verified_name?: string; quality_rating?: string }
interface MetaErrorResponse { error?: { message?: string; code?: number; type?: string } }
async function throwMetaError(response: Response, fallback: string): Promise<never> { let message = fallback; try { const data = (await response.json()) as MetaErrorResponse; if (data.error?.message) message = data.error.message } catch {}; throw new Error(message) }

export interface VerifyPhoneNumberArgs { phoneNumberId: string; accessToken: string }
export async function verifyPhoneNumber(args: VerifyPhoneNumberArgs): Promise<MetaPhoneInfo> { const response = await resilientFetch(`${META_API_BASE}/${args.phoneNumberId}?fields=id,display_phone_number,verified_name,quality_rating`, { headers: { Authorization: `Bearer ${args.accessToken}` } }); if (!response.ok) await throwMetaError(response, `Meta API error: ${response.status}`); return response.json() }
export interface RegisterPhoneNumberArgs { phoneNumberId: string; accessToken: string; pin: string }
export interface RegisterPhoneNumberResult { success: boolean; alreadyRegistered: boolean }
export async function registerPhoneNumber(args: RegisterPhoneNumberArgs): Promise<RegisterPhoneNumberResult> { const response = await resilientFetch(`${META_API_BASE}/${args.phoneNumberId}/register`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${args.accessToken}` }, body: JSON.stringify({ messaging_product: 'whatsapp', pin: args.pin }) }); if (response.ok) return { success: true, alreadyRegistered: false }; let data: { error?: { message?: string } } = {}; try { data = await response.json() } catch {}; const message = data.error?.message ?? `Meta API error: ${response.status}`; if (/already.*registered/i.test(message)) return { success: true, alreadyRegistered: true }; throw new Error(message) }
export interface SubscribeWabaToAppArgs { wabaId: string; accessToken: string }
export async function subscribeWabaToApp(args: SubscribeWabaToAppArgs): Promise<void> { const response = await resilientFetch(`${META_API_BASE}/${args.wabaId}/subscribed_apps`, { method: 'POST', headers: { Authorization: `Bearer ${args.accessToken}` } }); if (!response.ok) await throwMetaError(response, `Meta API error: ${response.status}`) }
export interface GetSubscribedAppsArgs { wabaId: string; accessToken: string }
export interface SubscribedApp { whatsapp_business_api_data?: { id?: string; name?: string; link?: string } }
export async function getSubscribedApps(args: GetSubscribedAppsArgs): Promise<SubscribedApp[]> { const response = await resilientFetch(`${META_API_BASE}/${args.wabaId}/subscribed_apps`, { headers: { Authorization: `Bearer ${args.accessToken}` } }); if (!response.ok) await throwMetaError(response, `Meta API error: ${response.status}`); const data = (await response.json()) as { data?: SubscribedApp[] }; return data.data ?? [] }

export interface SendTextMessageArgs { phoneNumberId: string; accessToken: string; to: string; text: string; contextMessageId?: string }
export async function sendTextMessage(args: SendTextMessageArgs): Promise<MetaSendResult> { const body: Record<string, unknown> = { messaging_product: 'whatsapp', recipient_type: 'individual', to: args.to, type: 'text', text: { body: args.text } }; if (args.contextMessageId) body.context = { message_id: args.contextMessageId }; const response = await resilientFetch(`${META_API_BASE}/${args.phoneNumberId}/messages`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${args.accessToken}` }, body: JSON.stringify(body) }); if (!response.ok) await throwMetaError(response, `Meta API error: ${response.status}`); const data = await response.json(); return { messageId: data.messages[0].id } }
export type MediaKind = 'image' | 'video' | 'document' | 'audio'
export interface SendMediaMessageArgs { phoneNumberId: string; accessToken: string; to: string; kind: MediaKind; link: string; caption?: string; filename?: string; contextMessageId?: string }
export async function sendMediaMessage(args: SendMediaMessageArgs): Promise<MetaSendResult> { if (!args.link) throw new Error('sendMediaMessage requires a link.'); const media: Record<string, unknown> = { link: args.link }; if (args.caption && args.kind !== 'audio') media.caption = args.caption; if (args.kind === 'document' && args.filename) media.filename = args.filename; const body: Record<string, unknown> = { messaging_product: 'whatsapp', recipient_type: 'individual', to: args.to, type: args.kind, [args.kind]: media }; if (args.contextMessageId) body.context = { message_id: args.contextMessageId }; const response = await resilientFetch(`${META_API_BASE}/${args.phoneNumberId}/messages`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${args.accessToken}` }, body: JSON.stringify(body) }); if (!response.ok) await throwMetaError(response, `Meta API error: ${response.status}`); const data = await response.json(); return { messageId: data.messages[0].id } }

export interface SendTemplateMessageArgs { phoneNumberId: string; accessToken: string; to: string; templateName: string; language?: string; params?: string[]; template?: MessageTemplate; messageParams?: SendTimeParams; contextMessageId?: string }
export async function sendTemplateMessage(args: SendTemplateMessageArgs): Promise<MetaSendResult> { const payload: Record<string, unknown> = { name: args.templateName, language: { code: args.language ?? 'en_US' } }; if (args.template) { const components = buildSendComponents(args.template, { body: args.messageParams?.body ?? args.params, headerText: args.messageParams?.headerText, headerMediaUrl: args.messageParams?.headerMediaUrl, headerMediaId: args.messageParams?.headerMediaId, buttonParams: args.messageParams?.buttonParams }); if (components.length) payload.components = components } else if (args.params?.length) payload.components = [{ type: 'body', parameters: args.params.map((p) => ({ type: 'text', text: String(p) })) }]; const body: Record<string, unknown> = { messaging_product: 'whatsapp', recipient_type: 'individual', to: args.to, type: 'template', template: payload }; if (args.contextMessageId) body.context = { message_id: args.contextMessageId }; const response = await resilientFetch(`${META_API_BASE}/${args.phoneNumberId}/messages`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${args.accessToken}` }, body: JSON.stringify(body) }); if (!response.ok) await throwMetaError(response, `Meta API error: ${response.status}`); const data = await response.json(); return { messageId: data.messages[0].id } }

export interface UploadResumableMediaArgs { appId: string; accessToken: string; fileName: string; mimeType: string; bytes: Uint8Array }
export async function uploadResumableMedia(args: UploadResumableMediaArgs): Promise<{ handle: string }> { const params = new URLSearchParams({ file_name: args.fileName, file_length: String(args.bytes.byteLength), file_type: args.mimeType, access_token: args.accessToken }); const start = await resilientFetch(`${META_API_BASE}/${args.appId}/uploads?${params}`, { method: 'POST' }); if (!start.ok) await throwMetaError(start, `Resumable upload start failed: ${start.status}`); const session = (await start.json()) as { id?: string }; if (!session.id) throw new Error('Resumable upload did not return a session id.'); const upload = await resilientFetch(`${META_API_BASE}/${session.id}`, { method: 'POST', headers: { Authorization: `OAuth ${args.accessToken}`, file_offset: '0' }, body: args.bytes as unknown as BodyInit }); if (!upload.ok) await throwMetaError(upload, `Resumable upload failed: ${upload.status}`); const data = (await upload.json()) as { h?: string }; if (!data.h) throw new Error('Resumable upload did not return a file handle.'); return { handle: data.h } }
export interface SubmitMessageTemplateArgs { wabaId: string; accessToken: string; payload: MetaTemplateSubmitPayload }
export interface SubmitMessageTemplateResult { id: string; status: string; category?: string }
export async function submitMessageTemplate(args: SubmitMessageTemplateArgs): Promise<SubmitMessageTemplateResult> { const response = await resilientFetch(`${META_API_BASE}/${args.wabaId}/message_templates`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${args.accessToken}` }, body: JSON.stringify(args.payload) }); if (!response.ok) await throwMetaError(response, `Meta API error: ${response.status}`); const data = await response.json(); if (!data?.id) throw new Error('Meta accepted the template but returned no id.'); return { id: String(data.id), status: typeof data.status === 'string' ? data.status : 'PENDING', category: typeof data.category === 'string' ? data.category : undefined } }
export interface EditMessageTemplateArgs { metaTemplateId: string; accessToken: string; components: MetaTemplateSubmitPayload['components']; category?: MetaTemplateSubmitPayload['category'] }
export interface EditMessageTemplateResult { success: boolean }
export async function editMessageTemplate(args: EditMessageTemplateArgs): Promise<EditMessageTemplateResult> { const body: Record<string, unknown> = { components: args.components }; if (args.category) body.category = args.category; const response = await resilientFetch(`${META_API_BASE}/${args.metaTemplateId}`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${args.accessToken}` }, body: JSON.stringify(body) }); if (!response.ok) await throwMetaError(response, `Meta API error: ${response.status}`); const data = await response.json().catch(() => ({})); return { success: data?.success !== false } }
export interface DeleteMessageTemplateArgs { wabaId: string; accessToken: string; name: string; metaTemplateId?: string }
export async function deleteMessageTemplate(args: DeleteMessageTemplateArgs): Promise<void> { const params = new URLSearchParams({ name: args.name }); if (args.metaTemplateId) params.set('hsm_id', args.metaTemplateId); const response = await resilientFetch(`${META_API_BASE}/${args.wabaId}/message_templates?${params}`, { method: 'DELETE', headers: { Authorization: `Bearer ${args.accessToken}` }); if (response.status === 404) return; if (!response.ok) await throwMetaError(response, `Meta API error: ${response.status}`) }
export interface SendReactionMessageArgs { phoneNumberId: string; accessToken: string; to: string; targetMessageId: string; emoji: string }
export async function sendReactionMessage(args: SendReactionMessageArgs): Promise<MetaSendResult> { const response = await resilientFetch(`${META_API_BASE}/${args.phoneNumberId}/messages`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${args.accessToken}` }, body: JSON.stringify({ messaging_product: 'whatsapp', recipient_type: 'individual', to: args.to, type: 'reaction', reaction: { message_id: args.targetMessageId, emoji: args.emoji } }) }); if (!response.ok) await throwMetaError(response, `Meta API error: ${response.status}`); const data = await response.json(); return { messageId: data.messages[0].id } }

export const INTERACTIVE_LIMITS = { maxButtons: 3, buttonTitleMaxLength: 20, maxListSections: 10, maxListRowsTotal: 10, listRowTitleMaxLength: 24, listRowDescriptionMaxLength: 72, bodyMaxLength: 1024, footerMaxLength: 60, headerTextMaxLength: 60 } as const
export interface InteractiveButton { id: string; title: string }
export interface SendInteractiveButtonsArgs { phoneNumberId: string; accessToken: string; to: string; bodyText: string; headerText?: string; footerText?: string; buttons: InteractiveButton[]; contextMessageId?: string }
export async function sendInteractiveButtons(args: SendInteractiveButtonsArgs): Promise<MetaSendResult> { if (!args.bodyText || args.bodyText.length > 1024) throw new Error('Interactive bodyText is invalid.'); if (args.headerText && args.headerText.length > 60) throw new Error('Interactive headerText is invalid.'); if (args.footerText && args.footerText.length > 60) throw new Error('Interactive footerText is invalid.'); if (args.buttons.length < 1 || args.buttons.length > 3) throw new Error('Interactive button count is invalid.'); const ids = new Set<string>(); for (const b of args.buttons) { if (!b.id || ids.has(b.id) || !b.title || b.title.length > 20) throw new Error('Interactive button is invalid.'); ids.add(b.id) } const interactive: Record<string, unknown> = { type: 'button', body: { text: args.bodyText }, action: { buttons: args.buttons.map((b) => ({ type: 'reply', reply: { id: b.id, title: b.title } })) } }; if (args.headerText) interactive.header = { type: 'text', text: args.headerText }; if (args.footerText) interactive.footer = { text: args.footerText }; const body: Record<string, unknown> = { messaging_product: 'whatsapp', recipient_type: 'individual', to: args.to, type: 'interactive', interactive }; if (args.contextMessageId) body.context = { message_id: args.contextMessageId }; const response = await resilientFetch(`${META_API_BASE}/${args.phoneNumberId}/messages`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${args.accessToken}` }, body: JSON.stringify(body) }); if (!response.ok) await throwMetaError(response, `Meta API error: ${response.status}`); const data = await response.json(); return { messageId: data.messages[0].id } }
export interface InteractiveListRow { id: string; title: string; description?: string }
export interface InteractiveListSection { title?: string; rows: InteractiveListRow[] }
export interface SendInteractiveListArgs { phoneNumberId: string; accessToken: string; to: string; bodyText: string; buttonLabel: string; headerText?: string; footerText?: string; sections: InteractiveListSection[]; contextMessageId?: string }
export async function sendInteractiveList(args: SendInteractiveListArgs): Promise<MetaSendResult> { if (!args.bodyText || args.bodyText.length > 1024 || !args.buttonLabel || args.buttonLabel.length > 20 || args.sections.length < 1 || args.sections.length > 10) throw new Error('Interactive list payload is invalid.'); const total = args.sections.reduce((sum, s) => sum + s.rows.length, 0); if (total < 1 || total > 10) throw new Error('Interactive list row count is invalid.'); const ids = new Set<string>(); for (const s of args.sections) for (const r of s.rows) { if (!r.id || ids.has(r.id) || !r.title || r.title.length > 24 || (r.description && r.description.length > 72)) throw new Error('Interactive list row is invalid.'); ids.add(r.id) } const interactive: Record<string, unknown> = { type: 'list', body: { text: args.bodyText }, action: { button: args.buttonLabel, sections: args.sections.map((s) => ({ ...(s.title ? { title: s.title } : {}), rows: s.rows.map((r) => ({ id: r.id, title: r.title, ...(r.description ? { description: r.description } : {}) })) })) } }; if (args.headerText) interactive.header = { type: 'text', text: args.headerText }; if (args.footerText) interactive.footer = { text: args.footerText }; const body: Record<string, unknown> = { messaging_product: 'whatsapp', recipient_type: 'individual', to: args.to, type: 'interactive', interactive }; if (args.contextMessageId) body.context = { message_id: args.contextMessageId }; const response = await resilientFetch(`${META_API_BASE}/${args.phoneNumberId}/messages`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${args.accessToken}` }, body: JSON.stringify(body) }); if (!response.ok) await throwMetaError(response, `Meta API error: ${response.status}`); const data = await response.json(); return { messageId: data.messages[0].id } }
export interface GetMediaUrlArgs { mediaId: string; accessToken: string }
export async function getMediaUrl(args: GetMediaUrlArgs): Promise<{ url: string; mimeType: string; fileSize: number | null }> { const response = await resilientFetch(`${META_API_BASE}/${args.mediaId}`, { headers: { Authorization: `Bearer ${args.accessToken}` } }); if (!response.ok) await throwMetaError(response, `Media fetch failed: ${response.status}`); const data = await response.json(); if (!data.url) throw new Error('Media URL not found in Meta response'); const size = Number(data.file_size); return { url: data.url, mimeType: data.mime_type || 'application/octet-stream', fileSize: Number.isFinite(size) && size >= 0 ? size : null } }
export interface DownloadMediaArgs { downloadUrl: string; accessToken: string }
export async function downloadMedia(args: DownloadMediaArgs): Promise<{ buffer: Buffer; contentType: string }> { const response = await resilientFetch(args.downloadUrl, { headers: { Authorization: `Bearer ${args.accessToken}` } }); if (!response.ok) throw new Error(`Media download failed: ${response.status}`); const contentType = response.headers.get('content-type') || 'application/octet-stream'; const buffer = Buffer.from(await response.arrayBuffer()); return { buffer, contentType } }
